### ISSUE TITLE
IPC: Top-down proof of finality and cross-net message execution

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/fendermint#154]
Related #153 

For the execution of top-down messages, validators in the child subnets are syncing with the parent, however, they may see a different heaviest height as being final, and thus, a different set of top-down messages committed in the parent and queued for execution in the child. 

To reconcile the view of all the validators, they should all vote for the finality that they see in the parent, and only if a majority of them see a specific height the top-down messages for that height are executed in the child. To avoid this process from consuming gas, we can execute top-down messages with the proof-of-finality implicitly. We may be able to link this process (if needed) with the updates of the on-chain membership set info in teh gateway from #153 

In the native actors, we currently have a really inefficient approach that we can probably improve further now with Fendermint.

## Updated design (after CoLo sync)
_(each bullet point can be extracted into its own implementation issue/ticket)_
- [ ] Every `n` messages or `e` epochs (whatever happens first) validators in the child subnet will create a new data structure including the latest height that they see as final in the parent and will broadcast a signed vote for that finality information. Validators can pick up this information from some endpoint they trust to the parent or their IPC agent. 

- [ ] All validators implement a protocol handler that is listening to new votes being broadcast for top-down finality information. They will collect this votes locally in order to build a proof of finality through a majority multisig with the votes for the finality information. We may want to have an independent topic to exchange this broadcast information per subnet separate from a (optional) bottom-up topic.

- [ ]  Once any of the validators was able to collect enough votes to vote the proof-of-finality, they will propose it as part of the next block. When the validators see the PoF in the block they will check the multisig, and the finality information they see in the parent, and either accept the block or reject it (in which case, if a majority doesn't accept the block, the PoF will have to be proposed in some other block).

- [ ] Through the PoF Fendermint is able to know the latest header that is considered final by the validators of the child subnet. This information can be used to either:
  - Automatically execute all the ordered top-down messages up to the height that is seen as final
  - Or in an alternative design proposed by @guy-goren, accept the submission of unordered top-down messages for execution

- [ ] Every time there is a new membership change in the parent, a new top-down message for a membership change will be included in the top-down queue to trigger the reconfiguration in the child. This messages are propagated and triggered in the same way as any other top-down message (see #153)

- [ ]  The validators whose votes were included in as part of the PoF will be conveniently rewarded when the information is committed on-chain.

**Comment by aakoshh** [comment]
This is the area where in my roadmap I proposed the two tier transaction submission mechanism:
1. Validators or relayers include top-down messages (the CID of it) for resolution
2. Once resolved, validators include the CID of the top-down message for execution; we use the `process_proposal` method to only vote if they are resolved and final.

For the second part, the _IPLD Resolver_ library also supports voting via the library, so it is possible to collect a quorum in the background, this "proof of finality". The benefit of that is that it would not have a chance to stall consensus, ie. it wouldn't stop the whole block from being executed because it was proposed too early, just result in an invalid transaction if the quorum hasn't been reached.

**Comment by aakoshh** [comment]
We might ask why should we include a message _for resolution_ into the blocks at all, why not manage this completely outside the realm of transactions? The advantage I see is the option to record messages being resolved in the ledger, so after a restart we have an obvious place to retrieve them from.

**Comment by adlrocha** [comment]
After a sync discussion with @aakoshh and @cryptoAtwill this is the proposal for #153 and #154. The goal is to agree on the high-level design described below and extract a set of low-level tickets for the implementation. 

## Top-down information exchange
There two types of important information that needs to be propagated from parent to child.
- The list of top-down messages that have been finalized in the parent and that can be executed in the child. 
- Information about the latest valid membership set of the child committed in the parent.

Fendermint (and any other peer implementation like Eudico) need to collect this information from the parent to trigger a reconfiguration and execute the messages.

The proposal is to wrap this information from the parent in periodic __top-down blocks__ _(let's not call them top-down checkpoints, as we are actually not checkpointing anything from the parent to the child)._
```rust
pub TopDownBlock struct {
  // parent height for the block being voted and seen as final.
  pub height: u64
  // list of top-down messages seen as final for that height.
  pub top_down_message: Vec<IPCMessage>
  // Latest membership information (internally, MembershipSet includes
  // information about the sequence number a list of validators. 
  // (see agent for additional info). 
  pub membership_info: MembershipSet
}
```
The top-down block includes information about the latest top-down messages, the height of the block seen as final in the parent for which this information belongs, and information about the latest membership for the subnet.

### Parent View
Fendermint will include a `ParentView` abstraction that exposes an interface for Fendermint to be able to query information that from the parent that can be considered final:
- New final membership configuration
- Information about top-down messages that are final
- Anything else?

I would suggest wrapping all of this information into top-down blocks that can be easily signed, propagated and potential identified through their CID. The `ParentView` can interact with different subsystems to get this information. Initially I would suggest directly using the IPC agent to fetch top-down blocks, but the IPLD Resolver could also be used for this.

### Commitment of top-down blocks
For a top-down block to be committed in the child subnet in order to trigger the corresponding membership changes and message execution, a majority of the validators of the child subnet must see this information as final in the parent.
- Every validator periodically queries their `ParentView` for an up-to-date top-down block with the information that it sees final at a certain height. This is something that we can discuss, but we can set a top-down period to determine how often top-down blocks should be assembled from final information in the parent.
- Validators will propose top-down blocks as part of their block proposal. In order for the rest of the validators to vote for a block will query their `ParentView` to see if they see that top-down block as final also in the parent. If a majority of the validators vote for this proposal, the top-down block is accepted and conveniently executed.

### Alternative designs.
What if a top-down block is never voted as part of the block? This could affect the liveness of the subnet. Other options we can use to prevent this is to: 
- Collect off-chain votes for top-down blocks and once a majority of votes are collected propose it as part of the block. 
- Validators include vote transactions as part of the block that the rest of the validators queue locally. When enough votes have been cast for a top-down block, its side-effects are conveniently triggered.

Some of these alternative designs are explored in more detail in this [doc](https://docs.google.com/document/d/1px9BLPEJONhA4LdUn751YFc0u-WQTjIuqL4XHw9R0Xk/edit#heading=h.lqa9x0ccs6ny)

### Implementation notes.
- This may require changes in `set_membership` a the submission of top-down checkpoints in the IPC gateway contract. 
- `set_membership` and top-down checkpoint submissions are currently decoupled. With this new design we may be able to couple both in the execution of top-down checkpoints. 
- Slight changes may also be required in the agent to be able to query and provide this top-down blocks.
- We want the execution of top-down blocks to be performed implicitly (so it doesn't cost any gas).
- We may be able to leverage the IPLD resolver for the off-chain voting proposal (@aakoshh to extend the design)

**Comment by aakoshh** [comment]
Great summary @adlrocha :+1: 

To be clear, is the `TopDownBlock` assembled in the parent ledger explicitly, or is it something that the child validator agents are supposed to assemble? 

1. If it was available in the parent ledger, then the parent validators already had consensus about its content, which would be a deterministic function of the top-down messages included in the parent ledger and the membership changes. In this case it would be viable to go with the story where a subnet validator proposes the resolution/execution of a CID of a `TopDownBlock` at height H in the parent chain, and everyone else just needs to verify that this CID is the one they see and it's final and available. 
2. If the agents assemble this block, then every agent has to do it on their own, independently, and vote on the availability and finality of every individual included message, but also that there was no censorship, by the virtue of everyone having assembled the same exact `TopDownBlock` up to height H. Under this scenario voting about CIDs is a bit different because unless you already have a CID, there's no point trying to retrieve it: you have to construct the `TopDownBlock` on your own anyway to validate it. 

I think that ideally the IPC subnet actors would construct this block on the parent ledger, to keep things simple for everyone. WDYT?

**Comment by aakoshh** [comment]
As a reminder, if we wanted to use the _IPLD Resolver_ for circulating votes up front, we can use 
* the [Client::publish_vote](https://github.com/aakoshh/ipc-ipld-resolver/blob/main/src/client.rs#L85) method to gossip votes about CIDs, with a custom label
* the [Service::subscribe](https://github.com/aakoshh/ipc-ipld-resolver/blob/main/src/service.rs#L233) method to receive [VoteRecord](https://github.com/aakoshh/ipc-ipld-resolver/blob/main/src/service.rs#L105) events, the aggregation of which the consumer would have to implement

**Comment by cryptoAtwill** [comment]
For `membership_info`, maybe we can also consider making it reflecting changes and mark it as Option. The changes in membership should not be that frequent. If we store the changes, it could be more storage friendly.

**Comment by adlrocha** [comment]
Superseded by https://github.com/consensus-shipyard/fendermint/issues/302
