### ISSUE TITLE
IPC: Maintain circ_supply and base_fee

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#19]
As a follow up to https://github.com/consensus-shipyard/fendermint/pull/14 figure out how to update the `circ_supply`. Are there tokens issued during FVM execution? There are burn fields, so the amount might decrease.

**Comment by adlrocha** [comment]
Related: https://github.com/consensus-shipyard/fendermint/issues/169

As discussed sync with @guy-goren, our reference implementation will set `base_fee=0` (although we will still allow subnet deployers to choose a different value). 

For the circulating supply, the execution of every new cross-net message will increase the value in the state so we can have an accurate value of the circulating supply of the subnet.

We won't be following the EIP1559 gas model (we only leverage the interface to interact with the system), which means that no funds will be burnt, and we will reward the gas fees equally to all validators (#169), except a 1% tax that is sent to the governance account in the subnet.
