### ISSUE TITLE
Method in the Gateway to return the current validator set

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#245]
At the end of the checkpointing period (typically called epoch), Fendermint needs to return to CometBFT the changes in the power table. For this it would help if the Gateway actor could return the current power table, so that we can calculate the delta.

That's because CometBFT expects updates, so if we currently have `{A: 1, B: 2}` and we want to transition to `{B: 3, C: 2}` then we need to give CometBFT an update of `{A: 0, B: 3, C:2}`, that is, not only do we say something about the validators in the next set, we also have to remove the previous ones if they are not in the next set.

**Comment by dnkolegov** [comment]
This is being addressed in https://github.com/consensus-shipyard/ipc-solidity-actors/pull/200

**Comment by aakoshh** [comment]
@dnkolegov posited taking a page from the book of the Gravity Bridge and only storing hashes of the validator sets. IIUC the way it works there is that in the Solidity contract only a hash of the validator set is stored, and when a checkpoint is sent the whole validator set is part of it, checked against the hash, and then the power threshold can be tested on the inputs, rather than against a stored configuration. 

The situation is somewhat different than ours, because Tendermint merely informs the Solidity contract about what's going on, while in our case the validator set is produced on the parent, assigned an ID, sent to the child, who then uses this ID to refer to it back. 

Nevertheless it's true that currently we store entire validator sets and we don't have to:
* @cryptoAtwill passes in the whole validator set even if it did not change since the last finality (but the configuration ID is not checked, which is is a [problem](https://github.com/consensus-shipyard/ipc-solidity-actors/pull/200/files#r1324702529). 
* The contract stores the validator set, which we will need when the contract needs to check whether signature submissions should be accepted in #249 
* Retrieving past validator set configurations is also required after a restart, when the node has to decide if it has to re-submit a signature in #259  
* But, we can always ask CometBFT itself [through the RPC](https://docs.cometbft.com/v0.37/rpc/#/Info/validators) about who the validators were in the past, and we can restore the power table and pass it to the contract for signature validation.

So the Gateway doesn't have to remember the _history_ of the validator sets. It's enough if a checkpoint remembers the block height, and the configuration number; we can use that to retrieve the validator set from CometBFT to make decisions or pass it to the contract if needed, and use the configuration ID to communicate to the parent who signed. 

The parent has to remember the validator set, because after changes it has to be able to propose a new full set. 

The child has to keep the full _next_ validator set until the end of the checkpoint period, which is when it's activated, which means it has to be passed to CometBFT in full. 

So the proposed changes are:
1. Keep a full record of a single _next_ `Membership` record. 
2. Keep a value for the _current configuration number_ which does not change until the contract is instructed. 
3. Upon instruction to adtop the next validator set, return the one stored and overwrite the current configuration number.
4. Fendermint will turn to CometBFT instead of calling the method mentioned in this ticket.

**Comment by adlrocha** [comment]
Overall, I agree with the changes, I like this approach a lot. Just a double-check: 

> Keep a full record of a single next Membership record.

All of this applies to the child subnet, right?

**Comment by aakoshh** [comment]
> All of this applies to the child subnet, right?

Yes, this is to implement the bottom-up checkpoint period in the child subnet itself. 

For example say we produce a checkpoint in the child subnet every 1000 blocks, and our current configuration number is 1. We may receive a new configuration from the parent at block 275, 589, 865,  (confirguration 2, 3 and 4, respectively) but all we do with them is stick them into the _next_ slot, replacing the previous one,while leaving the configuration number at 1. When we reach block 1000, we tell the contract to do the membership transition, so it overwrites the configuration number 1 with 4 and returning the membership we stored in block 865. 

Then, we tell CometBFT what the changes are by comparing the validator set at block 1000 to the one in the return value to produce a changeset, and we construct a checkpoint record signed by the validators at block 1000, signing over their power to configuration number 4. We send this checkpoint to the parent.

**Comment by dnkolegov** [comment]
> The parent has to remember the validator set, because after changes it has to be able to propose a new full set.

Does the parent (SubnetActor) need to remember the history on validator sets?
