### ISSUE TITLE
Method in the Gateway to adopt and return the last accumulated validator set

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#246]
As the Fendermint interpreter, _during_ the checkpointing period I want to hand cross messages to the Gateway and expect it to _accumulate_ validator set changes without adopting them immediately. 

At the _end_ of the checkpointing period, I want to call a method on the Gateway which returns to me the _next_ validator set to adopt in the upcoming blocks, that is, the last finalized validator set in the parent, including its Configuration Number and the power table. I want the contract to remember and adopt this as the _current_ validator set from now on.

**Comment by dnkolegov** [comment]
It is being implemented here - https://github.com/consensus-shipyard/ipc-solidity-actors/tree/membership

You can use 

- `newMembership(uint64 n, FvmAddress[] memory validators, uint256[] memory weights)` to adopt a new membership (validator set) explicitly under SYSTEM actor privileges if needed
- `commitParentFinality(ParentFinality calldata finality, uint64 n, FvmAddress[] calldata validators, uint256[] calldata weights` to adopt a new membership along with a parent finality message under SYSTEM actor
- `getLastMembership` to return the last adopted membership
