### ISSUE TITLE
Create Checkpoint actor to accumulate signatures

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#247]
As a Fendermint interpreter, I want to be able to use a smart contract (actor) to store the checkpoints about _our own subnet_, while the validator signatures  are being accumulated. I want the contract to be able to emit events to which relayers can subscribe. 

I don't know if a Solidity or a built-in actor is better for this. The Solidity API can be used for subscriptions, but so can the Tendermint RPC. The checkpoint itself will either go as "full fat" Solidity message to Lotus, or a "low fat" message with a CID if the parent is Fendermint.

**Comment by aakoshh** [comment]
As per https://github.com/consensus-shipyard/fendermint/issues/245#issuecomment-1719024342 this method should take as input parameters the _past_ validator set, because the contract will not keep the history of the power table. Fendermint shall retrieve the validators from CometBFT based on the height indicated in the signature, and then the contract can check whether the signatory can legally submit signatures, it should remember whether it _has_ submitted one already, adjust the power, check for quorum, etc.

Some of these checks can be done in Fendermint too, but since the same checks need to be done in Solidity on the parent, why not do it in Solidity here too.

**Comment by dnkolegov** [comment]
> this method should take as input parameters the past validator set

1. We have a map signatures: `height => membership_hash => signatures`
2. We check that the signature is valid and was signed a validator from the input validator set.
3. We hash the input "the past validator set" (that is ordered and the same for all honest validators on a child subnet).
4. Store the signature signatures[height][hash] = signature

Then, we can garbage collect old signatures set from that map.

@aakoshh Is my understanding correct?

**Comment by aakoshh** [comment]
> We have a map signatures: height => membership_hash => signatures

I don't know why you would complicate things with a membership hash here. We need a list of checkpoints. True, at any height there can be at most one checkpoint, so you can store them indexed by height. But there is only one membership eligible to sign a checkpoints, so there's no reason to sub-index by its hash. Just store the actual checkpoint, which is a `struct` we have to come up with. 

> We check that the signature is valid and was signed a validator from the input validator set.

Yes that sounds right.

> We hash the input "the past validator set" (that is ordered and the same for all honest validators on a child subnet).

I don't think there is any need for this hashing. 

> Store the signature signatures[height][hash] = signature

I think that should be more like an append, not overwriting with the single input signature. 
Once again, no need for hashing, just store the list of signatures at the height the checkpoint belongs to.

> Then, we can garbage collect old signatures set from that map.

I am not sure at which point we can garbage collect signatures, I'd say we can postpone that for now. First let's get all the other stories completed.

**Comment by aakoshh** [comment]
IMO start with the definition of a `Checkpoint` and then we need two mappings: `height => Checkpoint` and `height => Signature[]`. Let's take it from there.

**Comment by dnkolegov** [comment]
Is being implemented here - https://github.com/consensus-shipyard/ipc-solidity-actors/pull/new/fendermint247
