### ISSUE TITLE
Method in Checkpoint actor to add new validator signature

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#249]
As a validator, I want to be able to create a Message to the Checkpoint actor created in #247 and broadcast it as a transaction to the CometBFT network with my signature over the checkpoint, and then I want the actor to accumulate such signatures _iff_:
* the signature is over an existing incomplete checkpoint added in #248
* the signatory was a validator in the checkpoint period

If adding the checkpoint brings the total power of signatories over the total in the checkpointing period, then the actor _should_ emit an event to signal to the relayers that the checkpoint has been signed by a quorum. After this the actor _may_ refuse to add more signatures, but this isn't crucial because any further signatures are visible in transactions and relayers can swap them out if they want, so we might as well add them. See #251

**Comment by aakoshh** [comment]
After much deliberation in https://github.com/consensus-shipyard/ipc-solidity-actors/pull/202 we agreed that we will implement the following check using Merkle proofs:

> the signatory was a validator in the checkpoint period

When the checkpoint is created in #248 it will include a Merkle tree of validator keys and weights, and during submission the validators have to provide a Merkle proof that they were part of the validator set eligible to sign that checkpoint. This way we don't have to store a history of membership snapshots. 

For Merkle trees, we will use https://github.com/OpenZeppelin/merkle-tree, or more precisely its Rust implementation https://github.com/literallymarvellous/merkle-tree-rs , which in Solidity can be checked with https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/MerkleProof.sol

We will use `["address", "uint256"]` for encoding the validator key and the weight. (NB CometBFT expects weights to be `u64`, so `uint64` should suffice as well). To obtain an `address` we will use `ethers` to hash the `Secp256k1` public key we give to CometBFT to use as validator key in the power table. 

We will use the corresponding secret key to sign the hash of the `Checkpoint` and send that signature in the method call. The Solidity contract will recover the `address` from the signature and the checkpoint hash (which it knows already from #248) and run the proof check using the recovered address, and the weight, which needs to be an input. 

The method signature should look like this:
```
addSignature(uint64 height, bytes32[] proof, u256 weight, bytes signature)
```

**Comment by dnkolegov** [comment]
PR https://github.com/consensus-shipyard/ipc-solidity-actors/pull/202
