### ISSUE TITLE
(Optional) Method in Checkpoint actor clear past checkpoints

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#250]
At some point, if we see that the checkpoint has been registered in the parent, we _may_ want to clear out past checkpoints to free up space in our ledger.

**Comment by dnkolegov** [comment]
Should we also have a variable `H` that means all checkpoints with height <= H were committed and removed?

**Comment by dnkolegov** [comment]
Drafted - https://github.com/consensus-shipyard/ipc-solidity-actors/pull/207
