### ISSUE TITLE
(Optional) Method in Checkpoint actor to check for quorum and emit signature

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#251]
This method is an optional way for _timing_ when the quorum even is emitted. The thinking is that we want to make the quorum as big as possible, so we don't want to emit the event as soon as quorum is reached and freeze it there. My first thought was maybe to call a method at the end of the block, although that's not a big delay. 

But as explained in #249 it makes even more sense to keep accumulating signatures and let the relayers decide when they send it, because they can modify the list of signatures anyway, it's malleable. We can offer more rewards for relaying with more signatures.

**Comment by dnkolegov** [comment]
In https://github.com/consensus-shipyard/ipc-solidity-actors/pull/202 the following is implemented:
`QuorumWeightUpdated` event is emitted every time a new signature is added after reaching the threshold weight.

**Comment by dnkolegov** [comment]
@aakoshh may we close it? Is it implemented as intended or not?

**Comment by aakoshh** [comment]
Yes, I think we can close it.
