### ISSUE TITLE
Method in Checkpoint actor to retrieve signatures

### ISSUE THREAD

**Issue by aakoshh** [consensus-shipyard/fendermint#294]
This is to enable the relayer to complete https://github.com/consensus-shipyard/fendermint/issues/257

**Comment by dnkolegov** [comment]
Implemented here - https://github.com/consensus-shipyard/ipc-solidity-actors/blob/bbf1d9b2bf7250a0c5432894e15ed5f4b0453692/src/gateway/GatewayGetterFacet.sol#L211

**Comment by aakoshh** [comment]
https://github.com/consensus-shipyard/ipc-solidity-actors/pull/218
