### ISSUE TITLE
Use bootstrap nodes for child subnets

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/fendermint#312]
## Background
As brought up by @aakoshh, we shouldn't expose validator's network addresses publicly to avoid potential attacks. This leaves us with the only option of using bootstrap nodes for new validators to be able to discover the rest of members in the subnet. 

## Solution
My proposed solution is to: 
* Allow validators to deploy their own bootstrap nodes and advertise them through the subnet actor in the parent.
* We should include a `set_bootstrap(net_address: String)` function in the the Subnet actor for validators to be able to add their bootstrap. 
* When a validator leaves the subnet, we should remove their bootstrap to ensure that we keep fresh bootsraps in the list. 
* As part of this task, we should also add some scripts that aide with the deployment of bootstraps, and test the configuration that we need to set in validators to enable an easy deployment of a child subnets infra. 

## Discussion
I don´t have a strong opinion on the fact that we are only allowing to set bootsraps to validators. It felt right to just allow running bootstraps with some "skin in the game" to avoid users DDoS with fake bootstraps, but we can simplify a bit the model if needed.

**Comment by aakoshh** [comment]
Just to move some of my comments here:
* My initial thought was an optional address at the time the subnet is created, but it's not clear who could change it later
* The validator's voluntary signaling answers that question
* The [IPLD Resolver](https://github.com/consensus-shipyard/ipc-ipld-resolver) gossips around which node can serve data for what subnets - if it was possible to derive a CometBFT address from the mutliaddress where the IPLD Resolver itself is listening, it could be used to discover nodes to connect to on any subnet. However, there is no guarantee that they have `pex` enabled, or they are running on the port we assume they do. Nevertheless this would mean there would be only 2 seed addresses for the entire hierarchy. 

At the risk of stating the obvious, these addresses should be removed if the validator leaves the subnet completely.

**Comment by dnkolegov** [comment]
> 
When a validator leaves the subnet, we should remove their bootstrap to ensure that we keep fresh bootsraps in the list.

What if there is only one bootstrap node and the corresponding validator is leaving?

**Comment by adlrocha** [comment]
> What if there is only one bootstrap node and the corresponding validator is leaving?

My take is that then validators should worry about booting up a new bootstrap if they want to be discoverable. We could think of an economic incentive for bootstrap, where validators with bootstrap get higher rewards, but at this point I would keep it simple and consider it a best effort system.

**Comment by dnkolegov** [comment]
Implemented https://github.com/consensus-shipyard/ipc-solidity-actors/pull/239

**Comment by adlrocha** [comment]
Closed by #
