### ISSUE TITLE
Create EthAccount at `0x00..00` + fix default sender address

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/fendermint#407]
[This PR](https://github.com/consensus-shipyard/fendermint/pull/375) made us default to the system actor address in masked ID form as a sender when no `from` address is provided to `eth_call`. That address is `0xff00..00`. However, clients expect this address to be `0x00..00` (the null Ethereum address). We need to do two things here:

1. Create an EthAccount actor with an f410 address equivalent to `0x00..00`. The actor ID does not matter. See how Lotus does that [here](https://github.com/filecoin-project/lotus/blob/master/chain/gen/genesis/genesis_eth.go).
2. Fix `eth_call` to use that address as the default sender.

**Comment by raulk** [comment]
@cryptoAtwill are you a good person to take this on?

**Comment by aakoshh** [comment]
> However, clients expect this address to be 0x00..00

@raulk where exactly do they expect to see this? Where do they observe `0xff00..00`?

**Comment by raulk** [comment]
Say, for example, that a contract returns the sender address as a return value. Clients will expect that address to be 0x00..00 when the "from" field was elided. It's a long-standing convention in Eth APIs that can break random things down the line if not honoured.
